{% set data= load_setup_py_data() %}
package:
  name: ts-observatory-control
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.5
    - astroquery
    - pandas
    - pydantic
    - scipy
    - healpy
    - ts-criopy
    - ts-xml {{ xml_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - numpy {{ numpy }}
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - numpy {{ numpy }}
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-conda-build =0.5
  run:
    - astroquery
    - numpy {{ numpy }}
    - pandas
    - pydantic
    - python {{ python }}
    - healpy
    - scipy
    - ts-criopy
    - ts-xml
    - ts-salobj

