{% set data= load_setup_py_data() %}
package:
  name: ts-observatory-control
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - TS_CONFIG_OCS_DIR
    - OSPL_HOME

test:
  requires:
    - ts-conda-build =0.3
    - astroquery
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - python
    - tests
    - setup.cfg
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
